### ISSUE TITLE
Limiting "attempts" value in "fastMutex.lock" function

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/mutex-browser#4] opened 2020-10-11 12:27 UTC
https://github.com/ProtonMail/mutex-browser/blob/cf7746e9dcb13d3837c3eaca86f7b6e713928164/src/fastMutex.ts#L62

The module falls back to `cookieMutex` for me due to the #3 and then `fastMutex.lock` call never gets resolved for me.

So maybe it worth liming the attempts count and when the algorithm reaches the limit it throws the error. That would allow earlier issues detection. You know, silent issues are normally hard to notice and debug.

**Comment by mmso** [comment] 2020-10-11 20:56
Yes definitely. I added a max limit in https://github.com/ProtonMail/mutex-browser/commit/48dfddfdf9d55efc8b22116799017d6174ed4d14.

However the problem of it never resolving sounds like it could be caused by something else. Is the cookie setting mechanism not working well in the environment it is being run in?

**Closed as completed by mmso** 2020-10-11 20:56 UTC

**Comment by vladimiry** [comment] 2020-10-11 21:08
> sounds like it could be caused by something else

Of course. I didn't point to the issue cause here but suggested making the potential infinity looping issue sound louder by introducing the iteration limit, so it's easier to notice the problematic looping. Then when the issue gets noticed it needs to be debugged which I didn't do (not planning yet) since I just ended up using a fixed indexedDB support test. The indexedDB-based mutex seems to work well for me, at least promises don't get into the continuously unresolved state like happens with the cookie-based mutex.

> Is the cookie setting mechanism not working well in the environment it is being run in?

It's the @electron environment, recent stable version.
